name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release
  VCPKG_COMMIT: "943c5ef1c8f6b5e6ced092b242c8299caae2ff01"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672
    steps:
    - uses: actions/checkout@v4

    - name: Install static analyzers
      run: sudo apt-get install clang-tidy cppcheck -y -q


    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: "${{ env.VCPKG_COMMIT }}"
        cache-version: "ci-ubuntu"
        cache-restore-keys: |
          vcpkg-Linux-ci-ubuntu-

    - name: Configure
      run: |
        cmake --preset=ci-ubuntu

    - name: Build
      run: cmake --build --preset=ci-ubuntu -j 2

    - name: Install
      run: cmake --install build --prefix prefix

    - name: Test
      working-directory: build
      env:
        AMQP_BROKER: "localhost"
      run: ctest --output-on-failure -C Release -j 2
